parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    _instanceof:
        ConnectHolland\UserBundle\Mailer\BaseEmail:
            calls:
                - method: setMailer
                  arguments:
                      - '@ConnectHolland\UserBundle\Mailer\Mailer'

    Symfony\Component\HttpKernel\UriSigner:
        arguments:
            - '%kernel.secret%'

    ConnectHolland\UserBundle\Mailer\Mailer:
        arguments:
            - '@mailer'
            - '%env(USERBUNDLE_FROM_EMAILADDRESS)%'
            - '@twig'

    ConnectHolland\UserBundle\Mailer\RegistrationEmail:
        arguments:
            - '@router'
            - '@Symfony\Component\HttpKernel\UriSigner'

    ConnectHolland\UserBundle\Mailer\ResetEmail:
        arguments:
            - '@router'
            - '@Symfony\Component\HttpKernel\UriSigner'

    ConnectHolland\UserBundle\Security\UserBundleAuthenticator:
        arguments:
            - '@doctrine'
            - '@router'
            - '@security.csrf.token_manager'
            - '@security.user_password_encoder.generic'
            - '@event_dispatcher'

    ConnectHolland\UserBundle\Controller\RegistrationController:
        arguments:
            - '@doctrine'
            - '@session'
            - '@event_dispatcher'
            - '@router'
            - '@twig'
        tags:
            - { name: controller.service_arguments }

    ConnectHolland\UserBundle\Controller\ResetController:
        arguments:
            - '@doctrine'
            - '@session'
            - '@event_dispatcher'
            - '@router'
            - '@twig'
        tags:
            - { name: controller.service_arguments }

    ConnectHolland\UserBundle\Controller\SecurityController:
        arguments:
            - '@security.authentication_utils'
            - '@form.factory'
            - '@twig'
        tags:
            - { name: controller.service_arguments }

    ConnectHolland\UserBundle\Repository\UserRepository:
        arguments:
            - '@doctrine'
        tags:
            - { name: doctrine.repository_service }

    ConnectHolland\UserBundle\Command\UserCreateCommand:
        public: true
        arguments:
            $eventDispatcher: '@event_dispatcher'
            $class: ~
        tags:
            - { name: console.command }

    ConnectHolland\UserBundle\EventSubscriber\AuthenticateUserSubscriber:
        arguments:
            - '@security.authentication.guard_handler'
            - '@ConnectHolland\UserBundle\Security\UserBundleAuthenticator'
        tags:
            - { name: kernel.event_subscriber }

    ConnectHolland\UserBundle\EventSubscriber\CreateUserSubscriber:
        arguments:
            - '@security.user_password_encoder.generic'
            - '@doctrine'
        tags:
            - { name: kernel.event_subscriber }

    ConnectHolland\UserBundle\EventSubscriber\UserLoginSubscriber:
        arguments:
            - '@doctrine'
        tags:
            - { name: kernel.event_subscriber }

    ConnectHolland\UserBundle\EventSubscriber\UserCreatedSubscriber:
        arguments:
            - '@ConnectHolland\UserBundle\Mailer\RegistrationEmail'
        tags:
            - { name: kernel.event_subscriber }

    ConnectHolland\UserBundle\EventSubscriber\ResetUserSubscriber:
        arguments:
            - '@doctrine'
        tags:
            - { name: kernel.event_subscriber }

    ConnectHolland\UserBundle\EventSubscriber\UserResetSubscriber:
        arguments:
            - '@ConnectHolland\UserBundle\Mailer\ResetEmail'
            - '@doctrine'
        tags:
            - { name: kernel.event_subscriber }

    ConnectHolland\UserBundle\Security\OAuthUserProvider:
        arguments:
            - '@doctrine'

    ConnectHolland\UserBundle\Routing\OAuthRouteLoader:
        public: true
        arguments:
            $resourceOwnerMaps: []
        tags:
            - { name: 'routing.loader' }

    connectholland_user.routing_oauth_route_loader: '@ConnectHolland\UserBundle\Routing\OAuthRouteLoader'

    ConnectHolland\UserBundle\Form\RegistrationType:
        public: true
        arguments:
            $class: ~
        tags:
            - { name: 'form.type' }

    ConnectHolland\UserBundle\Form\PasswordType:
        public: true
        arguments:
            $passwordRequirements: []
        tags:
            - { name: form.type }

    Rollerworks\Component\PasswordStrength\Validator\Constraints\P0wnedPasswordValidator:
        lazy: false
        arguments:
            $client: '@Rollerworks\Component\PasswordStrength\P0wnedPassword\Request\Client'
        tags:
            - { name: validator.constraint_validator }

    Rollerworks\Component\PasswordStrength\P0wnedPassword\Request\Client:
        lazy: false
        arguments:
            $client: '@httplug.client'
            $logger: '@logger'
