parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    ConnectHolland\UserBundle\Security\UserBundleAuthenticator: ~

    ConnectHolland\UserBundle\Controller\RegistrationController:
        tags:
            - { name: controller.service_arguments }

    ConnectHolland\UserBundle\Controller\SecurityController:
        tags:
            - { name: controller.service_arguments }

    ConnectHolland\UserBundle\Form\RegistrationFormType:
        tags:
            - { name: form.type }

    ConnectHolland\UserBundle\Repository\UserRepository: ~
